
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author nguyenhuuphu
 */
public class QuanLyMonHoc extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyMonHoc
     */
    private ArrayList<MonHoc> dsMonHoc = NganHangCauHoi.dsMonHoc();

    private void setData(int selectedIndexMonHoc) {
        if (selectedIndexMonHoc >= 0) {
            this.jText_tenMonHoc.setText(dsMonHoc.get(selectedIndexMonHoc).gettenMonHoc());
            this.jTex_mahocphan.setText(dsMonHoc.get(selectedIndexMonHoc).getmaHocPhan());
            this.jText_gioi_thieu.setText(dsMonHoc.get(selectedIndexMonHoc).getgioiThieu());
            this.jS_so_chuong.setValue((int) dsMonHoc.get(selectedIndexMonHoc).soLuongChuong());

        } else {
            this.jText_tenMonHoc.setText("");
            this.jTex_mahocphan.setText("");
            this.jText_gioi_thieu.setText("");
            this.jS_so_chuong.setValue(0);
        }
    }

    private void setData_list_monHoc() {
        this.jLi_dsMonHoc.setListData(NganHangCauHoi.toArrayString_MonHoc(dsMonHoc));
    }

    private MonHoc getData() {
        MonHoc monhocSelected = new MonHoc();
        monhocSelected.settenMonHoc(this.jText_tenMonHoc.getText());
        monhocSelected.setmaHocPhan(this.jTex_mahocphan.getText());
        monhocSelected.setgioiThieu(this.jText_gioi_thieu.getText());
        monhocSelected.setsoLuongChuong((int) this.jS_so_chuong.getValue());
        return monhocSelected;
    }

    public QuanLyMonHoc() {
        initComponents();
        this.setVisible(true);
        this.setLocation(100, 100);

        this.jLi_dsMonHoc.setListData(NganHangCauHoi.toArrayString_MonHoc(dsMonHoc));
        this.setData(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLi_dsMonHoc = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jS_so_chuong = new javax.swing.JSpinner();
        jText_tenMonHoc = new javax.swing.JTextField();
        jTex_mahocphan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jText_gioi_thieu = new javax.swing.JTextArea();
        jB_Luu = new javax.swing.JButton();
        jB_HUY = new javax.swing.JButton();
        jB_xoa_monHoc = new javax.swing.JButton();
        jL_them_monHoc = new javax.swing.JLabel();
        jB_OK = new javax.swing.JButton();
        jB_them = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Danh sách môn học");

        jLi_dsMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLi_dsMonHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jLi_dsMonHoc);

        jLabel2.setText("Tên môn học");

        jLabel3.setText("Mã học phần");

        jLabel4.setText("Số chương");

        jLabel5.setText("Giới thiệu");

        jText_gioi_thieu.setColumns(20);
        jText_gioi_thieu.setRows(5);
        jScrollPane2.setViewportView(jText_gioi_thieu);

        jB_Luu.setText("Lưu");
        jB_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_LuuActionPerformed(evt);
            }
        });

        jB_HUY.setText("Hủy");

        jB_xoa_monHoc.setText("Xóa môn học");
        jB_xoa_monHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_xoa_monHocActionPerformed(evt);
            }
        });

        jL_them_monHoc.setForeground(new java.awt.Color(51, 0, 255));
        jL_them_monHoc.setText("<html><u>Thêm môn học</html>");
        jL_them_monHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_them_monHocMouseClicked(evt);
            }
        });

        jB_OK.setText("OK");
        jB_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_OKActionPerformed(evt);
            }
        });

        jB_them.setText("Thêm");
        jB_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_themActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jB_OK))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jL_them_monHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_them)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jB_xoa_monHoc))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jS_so_chuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTex_mahocphan, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                    .addComponent(jText_tenMonHoc))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_Luu)
                                .addGap(18, 18, 18)
                                .addComponent(jB_HUY)
                                .addGap(57, 74, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jText_tenMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTex_mahocphan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jS_so_chuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_xoa_monHoc)
                    .addComponent(jL_them_monHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_them))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Luu)
                    .addComponent(jB_HUY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_OK)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jL_them_monHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_them_monHocMouseClicked
        // TODO add your handling code here:
        this.setData(-1);

    }//GEN-LAST:event_jL_them_monHocMouseClicked

    private void jB_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_themActionPerformed
        // TODO add your handling code here:
        MonHoc monhocthem = new MonHoc();

        monhocthem = this.getData();
        dsMonHoc.add(monhocthem);
        this.jLi_dsMonHoc.setListData(NganHangCauHoi.toArrayString_MonHoc(dsMonHoc));
        this.setData(dsMonHoc.size() - 1);
    }//GEN-LAST:event_jB_themActionPerformed

    private void jLi_dsMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLi_dsMonHocMouseClicked
        // TODO add your handling code here:
        int selectedIndex = this.jLi_dsMonHoc.getSelectedIndex();
        this.setData(selectedIndex);
    }//GEN-LAST:event_jLi_dsMonHocMouseClicked

    private void jB_xoa_monHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_xoa_monHocActionPerformed
        // TODO add your handling code here:
        int selectedIndexMonHoc = this.jLi_dsMonHoc.getSelectedIndex();
        this.dsMonHoc.remove(selectedIndexMonHoc);
        this.setData_list_monHoc();
        if (dsMonHoc.size() > 0) {
            this.setData(0);
        } else {
            this.setData(-1);
        }
    }//GEN-LAST:event_jB_xoa_monHocActionPerformed

    private void jB_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_LuuActionPerformed
        // TODO add your handling code here:
        int selectedIndexMonHoc = this.jLi_dsMonHoc.getSelectedIndex();
        MonHoc monhoc = dsMonHoc.get(selectedIndexMonHoc);
        monhoc.settenMonHoc(this.jText_tenMonHoc.getText());
        monhoc.setmaHocPhan(this.jTex_mahocphan.getText());
        monhoc.setgioiThieu(this.jText_gioi_thieu.getText());
        dsMonHoc.set(selectedIndexMonHoc, monhoc);
        this.setData(selectedIndexMonHoc);

    }//GEN-LAST:event_jB_LuuActionPerformed

    private void jB_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_OKActionPerformed
        // TODO add your handling code here:
        NganHangCauHoi.ghiRaObject(dsMonHoc);
        this.dispose();
    }//GEN-LAST:event_jB_OKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_HUY;
    private javax.swing.JButton jB_Luu;
    private javax.swing.JButton jB_OK;
    private javax.swing.JButton jB_them;
    private javax.swing.JButton jB_xoa_monHoc;
    private javax.swing.JLabel jL_them_monHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jLi_dsMonHoc;
    private javax.swing.JSpinner jS_so_chuong;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTex_mahocphan;
    private javax.swing.JTextArea jText_gioi_thieu;
    private javax.swing.JTextField jText_tenMonHoc;
    // End of variables declaration//GEN-END:variables
}
