
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author nguyenhuuphu
 */
public class QuanLyDeThi extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyDeThi
     */
    private ArrayList<DeThi> dsDeThi;
    private MonHoc monhoc;
    private int selectedIndex;

    private void setdsTenDeThi() {
        String[] list = new String[dsDeThi.size()];
        for (int i = 0; i < list.length; i++) {
            list[i] = dsDeThi.get(i).getmonHoc() + dsDeThi.get(i).getmaDe();
        }
        this.jList_dsDeThi.setListData(list);
    }

    public QuanLyDeThi(int selectedIndex) {
        this.selectedIndex = selectedIndex;
        this.setTitle("Quản lý đề thi");
        initComponents();
        this.setVisible(true);
        monhoc = NganHangCauHoi.dsMonHoc().get(selectedIndex);
        this.dsDeThi = NganHangCauHoi.docDSDeThituObject("dsDe" + monhoc.gettenMonHoc() + ".txt");
        setdsTenDeThi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jB_Tao_de_thi_tu_dong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_dsDeThi = new javax.swing.JList<>();
        jB_OK = new javax.swing.JButton();
        jB_Tao_de_thi_bang_tay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Quản lý đề thi");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Danh sách đề thi sẵn có");

        jB_Tao_de_thi_tu_dong.setBackground(new java.awt.Color(204, 255, 0));
        jB_Tao_de_thi_tu_dong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jB_Tao_de_thi_tu_dong.setText("Tạo đề thi tự động");
        jB_Tao_de_thi_tu_dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Tao_de_thi_tu_dongActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList_dsDeThi);

        jB_OK.setText("OK");
        jB_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_OKActionPerformed(evt);
            }
        });

        jB_Tao_de_thi_bang_tay.setBackground(new java.awt.Color(255, 255, 51));
        jB_Tao_de_thi_bang_tay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jB_Tao_de_thi_bang_tay.setText("Tạo đề thi bằng tay");
        jB_Tao_de_thi_bang_tay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Tao_de_thi_bang_tayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jB_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_Tao_de_thi_bang_tay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(jB_Tao_de_thi_tu_dong)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Tao_de_thi_bang_tay)
                    .addComponent(jB_Tao_de_thi_tu_dong))
                .addGap(18, 18, 18)
                .addComponent(jB_OK, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_OKActionPerformed
        // TODO add your handling code here:
        if (this.jList_dsDeThi.getSelectedIndex() >= 0) {
            new LamBaiThi(this.selectedIndex, this.jList_dsDeThi.getSelectedIndex());
    }//GEN-LAST:event_jB_OKActionPerformed
    }
    private void jB_Tao_de_thi_bang_tayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Tao_de_thi_bang_tayActionPerformed
        // TODO add your handling code here:
        SinhDeThiBangTay gd4 = new SinhDeThiBangTay(this.selectedIndex);
    }//GEN-LAST:event_jB_Tao_de_thi_bang_tayActionPerformed

    private void jB_Tao_de_thi_tu_dongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Tao_de_thi_tu_dongActionPerformed
        // TODO add your handling code here:
        SinhDeThiTuDong gd6 = new SinhDeThiTuDong(this.selectedIndex);

    }//GEN-LAST:event_jB_Tao_de_thi_tu_dongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_OK;
    private javax.swing.JButton jB_Tao_de_thi_bang_tay;
    private javax.swing.JButton jB_Tao_de_thi_tu_dong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList_dsDeThi;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
