
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author nguyenhuuphu
 */
public class SinhDeThiTuDong extends javax.swing.JFrame {

    /**
     * Creates new form SinhDeThiTuDong
     */
    private ArrayList<DeThi> dsDeThi = new ArrayList<DeThi>();
    private DeThi dethi;
    private MonHoc monhoc;
    private int selectedIndex;
    private String loaide;
    private String thutu;
    private ArrayList<CauHoi> dsCauHoiMon;

    private void setThongTinDeThi() {
        this.dethi.sethocKi(this.jTextField_Nam_hoc.getText());
        Integer i = Integer.valueOf(this.jTextField_Thoi_gian.getText());
        this.dethi.setthoiGian(i.intValue());
        String ki = new String();
        if (this.jRadio_ki1.isSelected()) {
            ki = "1";

        } else if (this.jRadio_ki2.isSelected()) {
            ki = "2";
        } else {
            ki = "hè";
        }
        this.dethi.setloaiKi(ki);
        dethi.setmonHoc(monhoc.gettenMonHoc());
        dethi.setmaDe(NganHangCauHoi.rand(100, 300));
    }

    public void setData_text_deThi() {
        if (dethi.soLuongCauHoi() == 0) {
            this.jText_deTHi.setText("");
            return;
        }
        StringBuffer buffer = new StringBuffer();
        buffer.append("Bài thi môn:" + this.dethi.getmonHoc());

        buffer.append("\nKì:" + this.dethi.getloaiKi() + "-Năm học:" + dethi.gethocKi() + "Mã đề:" + dethi.getmaDe());
        buffer.append("\nThời gian" + this.dethi.getthoiGian() + "\n");
        for (int i = 0; i < dethi.getdsCauHoi().size(); i++) {
            buffer.append("Câu " + (i + 1) + "(" + dethi.getdsCauHoi().get(i).getdiem() + "điểm)\n");
            buffer.append(dethi.getdsCauHoi().get(i).inCauHoi() + "\n");

            this.jText_deTHi.setText(buffer.toString());
        }
    }

    public void setData_dsCauHoi_deThi() {
        if (dethi.soLuongCauHoi() == 0) {
            String[] list = {""};
            this.jL_dsCauHoi.setListData(list);
        }
        String[] list = new String[dethi.getdsCauHoi().size()];
        for (int i = 0; i < dethi.getdsCauHoi().size(); i++) {
            list[i] = dethi.getdsCauHoi().get(i).gettenCauHoi();
        }
        this.jL_dsCauHoi.setListData(list);
    }

    public SinhDeThiTuDong(int selectedIndex) {
        this.selectedIndex = selectedIndex;
        initComponents();
        this.setLocation(100, 100);
        this.setVisible(true);
        this.monhoc = NganHangCauHoi.dsMonHoc().get(selectedIndex);
        this.dsDeThi = NganHangCauHoi.docDSDeThituObject("dsDe" + this.monhoc.gettenMonHoc() + ".txt");
        this.dsCauHoiMon = NganHangCauHoi.dsCauHoiMon(monhoc);
        this.loaide = "Trắc nghiệm và Tự luận";
        this.thutu = "riêng";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadio_Trac_nghiem = new javax.swing.JRadioButton();
        jRadio_Tu_luan = new javax.swing.JRadioButton();
        jRadio_ca_trac_nghiem_va_tu_luan = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadio_Chung = new javax.swing.JRadioButton();
        jRadio_Rieng = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jSpinner_So_Cau = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_Do_Kho = new javax.swing.JComboBox<>();
        jB_Tao_de_Thi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jL_dsCauHoi = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jText_deTHi = new javax.swing.JTextArea();
        jLable_CauHoiTuongDuong = new javax.swing.JLabel();
        jLabel_Xoa_cau_hoi = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Thoi_gian = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jRadio_ki1 = new javax.swing.JRadioButton();
        jRadio_ki2 = new javax.swing.JRadioButton();
        jRadio_ki_he = new javax.swing.JRadioButton();
        jTextField_Nam_hoc = new javax.swing.JTextField();
        jLabel_Xao_tron_cau_hoi = new javax.swing.JLabel();
        jLabel_Xuat_ra_file = new javax.swing.JLabel();
        jB_Luu = new javax.swing.JButton();
        jB_Huy = new javax.swing.JButton();
        jB_OK = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dạng đề thi");

        buttonGroup1.add(jRadio_Trac_nghiem);
        jRadio_Trac_nghiem.setText("Trắc nghiệm");
        jRadio_Trac_nghiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_Trac_nghiemActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio_Tu_luan);
        jRadio_Tu_luan.setText("Tự luận");
        jRadio_Tu_luan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_Tu_luanActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio_ca_trac_nghiem_va_tu_luan);
        jRadio_ca_trac_nghiem_va_tu_luan.setSelected(true);
        jRadio_ca_trac_nghiem_va_tu_luan.setText("Cả trắc nghiệm và tự luận");
        jRadio_ca_trac_nghiem_va_tu_luan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_ca_trac_nghiem_va_tu_luanActionPerformed(evt);
            }
        });

        jLabel2.setText("Hình thức");

        buttonGroup3.add(jRadio_Chung);
        jRadio_Chung.setText("Phần trắc nghiệm và tự luận chung");
        jRadio_Chung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_ChungActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadio_Rieng);
        jRadio_Rieng.setSelected(true);
        jRadio_Rieng.setText("Phần trắc nghiệm và tự luận riêng");
        jRadio_Rieng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_RiengActionPerformed(evt);
            }
        });

        jLabel3.setText("Số câu");

        jLabel4.setText("Độ khó");

        jComboBox_Do_Kho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bất kì", "De", "TrungBinh", "Kho" }));
        jComboBox_Do_Kho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Do_KhoActionPerformed(evt);
            }
        });

        jB_Tao_de_Thi.setText("Tạo đề thi");
        jB_Tao_de_Thi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Tao_de_ThiActionPerformed(evt);
            }
        });

        jLabel5.setText("Danh sách câu hỏi trong đề thi");

        jScrollPane1.setViewportView(jL_dsCauHoi);

        jText_deTHi.setColumns(20);
        jText_deTHi.setRows(5);
        jScrollPane2.setViewportView(jText_deTHi);

        jLable_CauHoiTuongDuong.setForeground(new java.awt.Color(51, 51, 255));
        jLable_CauHoiTuongDuong.setText("<html><u>Thay thế bằng câu hỏi tương đương");
        jLable_CauHoiTuongDuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLable_CauHoiTuongDuongMouseClicked(evt);
            }
        });

        jLabel_Xoa_cau_hoi.setForeground(new java.awt.Color(51, 51, 255));
        jLabel_Xoa_cau_hoi.setText("<html><u>Xóa câu hỏi khỏi đề thi");
        jLabel_Xoa_cau_hoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Xoa_cau_hoiMouseClicked(evt);
            }
        });

        jLabel8.setText("Thông tin đề thi");

        jLabel9.setText("Thời gian");

        jTextField_Thoi_gian.setText("60");

        jLabel30.setText("Năm học");

        jLabel11.setText("Kì");

        buttonGroup2.add(jRadio_ki1);
        jRadio_ki1.setSelected(true);
        jRadio_ki1.setText("1");

        buttonGroup2.add(jRadio_ki2);
        jRadio_ki2.setText("2");

        buttonGroup2.add(jRadio_ki_he);
        jRadio_ki_he.setText("Hè");

        jTextField_Nam_hoc.setText("2015-2016");

        jLabel_Xao_tron_cau_hoi.setForeground(new java.awt.Color(51, 51, 255));
        jLabel_Xao_tron_cau_hoi.setText("<html><u>Xáo trộn các câu hỏi trong đề thi");
        jLabel_Xao_tron_cau_hoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Xao_tron_cau_hoiMouseClicked(evt);
            }
        });

        jLabel_Xuat_ra_file.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_Xuat_ra_file.setText("<html><u>Xuất ra file");
        jLabel_Xuat_ra_file.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Xuat_ra_fileMouseClicked(evt);
            }
        });

        jB_Luu.setText("Lưu");
        jB_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_LuuActionPerformed(evt);
            }
        });

        jB_Huy.setText("Hủy");
        jB_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_HuyActionPerformed(evt);
            }
        });

        jB_OK.setText("OK");
        jB_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_OKActionPerformed(evt);
            }
        });

        jLabel6.setText("Phút");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(28, 28, 28)
                                        .addComponent(jRadio_Trac_nghiem))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSpinner_So_Cau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRadio_Chung)
                                            .addComponent(jComboBox_Do_Kho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabel4))
                            .addComponent(jLable_CauHoiTuongDuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Xoa_cau_hoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_Xao_tron_cau_hoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel_Xuat_ra_file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadio_Rieng)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jB_Tao_de_Thi)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadio_Tu_luan)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadio_ca_trac_nghiem_va_tu_luan)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadio_ki1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadio_ki2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadio_ki_he)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextField_Nam_hoc))
                                .addGap(333, 333, 333))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_Thoi_gian, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)))
                                .addGap(402, 402, 402)))
                        .addComponent(jB_Luu)
                        .addGap(18, 18, 18)
                        .addComponent(jB_Huy)
                        .addGap(46, 46, 46)
                        .addComponent(jB_OK))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadio_Trac_nghiem)
                    .addComponent(jRadio_Tu_luan)
                    .addComponent(jRadio_ca_trac_nghiem_va_tu_luan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadio_Chung)
                    .addComponent(jRadio_Rieng))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinner_So_Cau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox_Do_Kho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jB_Tao_de_Thi)
                        .addGap(10, 10, 10)))
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLable_CauHoiTuongDuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Xoa_cau_hoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextField_Thoi_gian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_Xao_tron_cau_hoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Xuat_ra_file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jTextField_Nam_hoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jRadio_ki1)
                            .addComponent(jRadio_ki2)
                            .addComponent(jRadio_ki_he))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jB_Huy)
                        .addComponent(jB_OK)
                        .addComponent(jB_Luu))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_Do_KhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Do_KhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_Do_KhoActionPerformed

    private void jRadio_Trac_nghiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_Trac_nghiemActionPerformed
        // TODO add your handling code here:
        this.buttonGroup3.clearSelection();
        this.jRadio_Chung.setEnabled(false);
        this.jRadio_Rieng.setEnabled(false);

        this.loaide = "Trắc nghiệm";
    }//GEN-LAST:event_jRadio_Trac_nghiemActionPerformed

    private void jRadio_Tu_luanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_Tu_luanActionPerformed
        // TODO add your handling code here:
        this.buttonGroup3.clearSelection();
        this.jRadio_Chung.setEnabled(false);
        this.jRadio_Rieng.setEnabled(false);

        this.loaide = "Tự luận";
    }//GEN-LAST:event_jRadio_Tu_luanActionPerformed

    private void jRadio_ca_trac_nghiem_va_tu_luanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_ca_trac_nghiem_va_tu_luanActionPerformed
        // TODO add your handling code here:
        this.jRadio_Rieng.setEnabled(true);
        this.jRadio_Chung.setEnabled(true);

        this.loaide = "Trắc nghiệm và Tự luận";
    }//GEN-LAST:event_jRadio_ca_trac_nghiem_va_tu_luanActionPerformed

    private void jRadio_ChungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_ChungActionPerformed
        // TODO add your handling code here:
        this.thutu = "chung";
    }//GEN-LAST:event_jRadio_ChungActionPerformed

    private void jRadio_RiengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_RiengActionPerformed
        // TODO add your handling code here:
        this.thutu = "riêng";
    }//GEN-LAST:event_jRadio_RiengActionPerformed

    private void jB_Tao_de_ThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Tao_de_ThiActionPerformed
        // TODO add your handling code here:
        int socau = (int) this.jSpinner_So_Cau.getValue();
        dethi = NganHangCauHoi.taoDeThiTuDong(monhoc, loaide, socau, thutu, this.jComboBox_Do_Kho.getSelectedItem().toString());
        this.setData_dsCauHoi_deThi();
        this.setThongTinDeThi();
        this.setData_text_deThi();
    }//GEN-LAST:event_jB_Tao_de_ThiActionPerformed

    private void jB_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_LuuActionPerformed
        // TODO add your handling code here:
        this.dsDeThi.add(dethi);
        NganHangCauHoi.ghiDeThiRaObject(dsDeThi);

    }//GEN-LAST:event_jB_LuuActionPerformed

    private void jB_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_OKActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jB_OKActionPerformed

    private void jB_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_HuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jB_HuyActionPerformed

    private void jLabel_Xuat_ra_fileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Xuat_ra_fileMouseClicked
        // TODO add your handling code here:
        dethi.inDeThi();
        dethi.inDapAn();
    }//GEN-LAST:event_jLabel_Xuat_ra_fileMouseClicked

    private void jLabel_Xao_tron_cau_hoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Xao_tron_cau_hoiMouseClicked
        // TODO add your handling code here:
        dethi.daoCauHoi();
        this.setData_dsCauHoi_deThi();
        this.setData_text_deThi();
    }//GEN-LAST:event_jLabel_Xao_tron_cau_hoiMouseClicked

    private void jLabel_Xoa_cau_hoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Xoa_cau_hoiMouseClicked
        // TODO add your handling code here:
        int selectedIndexCauHoi = this.jL_dsCauHoi.getSelectedIndex();
        dethi.xoaCauHoi(selectedIndexCauHoi);
        this.setData_dsCauHoi_deThi();
        this.setData_text_deThi();
    }//GEN-LAST:event_jLabel_Xoa_cau_hoiMouseClicked

    private void jLable_CauHoiTuongDuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLable_CauHoiTuongDuongMouseClicked
        // TODO add your handling code here:
        CauHoi ch = this.dethi.getdsCauHoi().get(this.jL_dsCauHoi.getSelectedIndex());
        CauHoi temp = NganHangCauHoi.cauHoiTuongDuong(ch, this.dsCauHoiMon);
        if (temp != null) {
            dethi.suaCauHoi(this.jL_dsCauHoi.getSelectedIndex(), temp);
        }
        this.setData_dsCauHoi_deThi();
        this.setData_text_deThi();
    }//GEN-LAST:event_jLable_CauHoiTuongDuongMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jB_Huy;
    private javax.swing.JButton jB_Luu;
    private javax.swing.JButton jB_OK;
    private javax.swing.JButton jB_Tao_de_Thi;
    private javax.swing.JComboBox<String> jComboBox_Do_Kho;
    private javax.swing.JList<String> jL_dsCauHoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Xao_tron_cau_hoi;
    private javax.swing.JLabel jLabel_Xoa_cau_hoi;
    private javax.swing.JLabel jLabel_Xuat_ra_file;
    private javax.swing.JLabel jLable_CauHoiTuongDuong;
    private javax.swing.JRadioButton jRadio_Chung;
    private javax.swing.JRadioButton jRadio_Rieng;
    private javax.swing.JRadioButton jRadio_Trac_nghiem;
    private javax.swing.JRadioButton jRadio_Tu_luan;
    private javax.swing.JRadioButton jRadio_ca_trac_nghiem_va_tu_luan;
    private javax.swing.JRadioButton jRadio_ki1;
    private javax.swing.JRadioButton jRadio_ki2;
    private javax.swing.JRadioButton jRadio_ki_he;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_So_Cau;
    private javax.swing.JTextField jTextField_Nam_hoc;
    private javax.swing.JTextField jTextField_Thoi_gian;
    private javax.swing.JTextArea jText_deTHi;
    // End of variables declaration//GEN-END:variables
}
