
import java.awt.Component;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author nguyenhuuphu
 */
public class SoanCauHoi extends javax.swing.JFrame {

    private MonHoc monhoc;
    private int selectedIndex;
    private ArrayList<CauHoi> dsCauHoi;
    private ArrayList<MonHoc> dsMonHoc = NganHangCauHoi.dsMonHoc();

    private void setData(int selectedIndexCauHoi) {
        if (selectedIndexCauHoi >= 0) {
            CauHoi ch = this.dsCauHoi.get(selectedIndexCauHoi);
            this.jTextArea1.setText(ch.gettenCauHoi());
            String[] dsDA = new String[ch.getsoLuongDapAn()];
            for (int i = 0; i < dsDA.length; i++) {
                if (ch instanceof CauHoiTN) {
                    dsDA[i] = ((CauHoiTN) ch).getdsDapAn().get(i);
                } else {
                    dsDA[i] = ((CauHoiTL) ch).getDapAn();
                }
            }
            this.jList2.setListData(dsDA);

        } else {
            this.jTextArea1.setText("");
            String[] a = {};
            this.jList2.setListData(a);
        }

    }

    private void setData_ds_CauHoi(ArrayList<CauHoi> dsCauHoi) {
        String[] dstenCauHoi = new String[dsCauHoi.size()];
        for (int i = 0; i < dstenCauHoi.length; i++) {
            dstenCauHoi[i] = dsCauHoi.get(i).gettenCauHoi();
        }
        this.jList1.setListData(dstenCauHoi);
    }

    public SoanCauHoi(int selectedIndex) {
        super("Soạn câu hỏi");
        this.selectedIndex = selectedIndex;
        this.monhoc = dsMonHoc.get(selectedIndex);
        this.setVisible(true);
        dsCauHoi = NganHangCauHoi.dsCauHoiMon(monhoc);
        String[] dstenCauHoi = NganHangCauHoi.toArrayString_dsCauHoiMon(monhoc);

        initComponents();
        this.jList1.setListData(dstenCauHoi);
        int sochuong = monhoc.soLuongChuong();
        for (int i = 0; i < sochuong; i++) {
            this.jCo_Chuong.addItem(monhoc.getdsChuong().get(i).gettenChuong());
        }
        this.setData(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel_them_cauHoi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCo_Chuong = new javax.swing.JComboBox<>();
        jCo_DoKho = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jB_OK = new javax.swing.JButton();
        jB_Luu = new javax.swing.JButton();
        jL_Xoa_CauHoi = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_Them_dap_an = new javax.swing.JTextField();
        jB_ThemDApan = new javax.swing.JButton();
        jB_sua_dap_an = new javax.swing.JButton();
        jCheckBox_dap_an_dung = new javax.swing.JCheckBox();
        jButton_them_cauHoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Danh sách câu hỏi");

        jLabel2.setText("Dạng câu hỏi");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Trăc nghiệm");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Tự luận");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Đề bài");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Các đáp án lựa chọn");

        jScrollPane3.setViewportView(jList2);

        jLabel_them_cauHoi.setForeground(new java.awt.Color(102, 102, 255));
        jLabel_them_cauHoi.setText("<html><u>Thêm câu hỏi</html>");
        jLabel_them_cauHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_them_cauHoiMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Chương");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Độ Khó");

        jLabel12.setText("<html><u>xóa</html>");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jCo_Chuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCo_Chuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCo_ChuongActionPerformed(evt);
            }
        });

        jCo_DoKho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCo_DoKho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "De", "TrungBinh", "Kho" }));
        jCo_DoKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCo_DoKhoActionPerformed(evt);
            }
        });

        jButton1.setText("Hủy");

        jB_OK.setText("OK");
        jB_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_OKActionPerformed(evt);
            }
        });

        jB_Luu.setText("Lưu");
        jB_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_LuuActionPerformed(evt);
            }
        });

        jL_Xoa_CauHoi.setForeground(new java.awt.Color(102, 102, 255));
        jL_Xoa_CauHoi.setText("<html><u>Xóa câu hỏi</html>");
        jL_Xoa_CauHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_Xoa_CauHoiMouseClicked(evt);
            }
        });

        jLabel11.setText("<html><u>Đảo đáp án</html>l>");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel13.setText("Thêm đáp án");

        jB_ThemDApan.setText("Thêm");
        jB_ThemDApan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ThemDApanActionPerformed(evt);
            }
        });

        jB_sua_dap_an.setText("Sửa");
        jB_sua_dap_an.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_sua_dap_anActionPerformed(evt);
            }
        });

        jCheckBox_dap_an_dung.setText("Đáp án đúng");

        jButton_them_cauHoi.setText("Thêm");
        jButton_them_cauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_them_cauHoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_them_cauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jLabel4))
                            .addComponent(jL_Xoa_CauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBox_dap_an_dung)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jB_Luu)
                                                .addGap(44, 44, 44)
                                                .addComponent(jButton1)
                                                .addGap(30, 30, 30))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jB_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCo_DoKho, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_Them_dap_an, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jB_ThemDApan)
                                                .addGap(18, 18, 18)
                                                .addComponent(jB_sua_dap_an)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCo_Chuong, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2))
                                    .addComponent(jButton_them_cauHoi, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jLabel2))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_them_cauHoi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_them_cauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_Xoa_CauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel13)
                        .addComponent(jTextField_Them_dap_an, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jB_ThemDApan)
                        .addComponent(jB_sua_dap_an))
                    .addComponent(jCo_Chuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCo_DoKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox_dap_an_dung)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Luu)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jB_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jCo_ChuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCo_ChuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCo_ChuongActionPerformed

    private void jCo_DoKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCo_DoKhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCo_DoKhoActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        String t = this.jList1.getSelectedValue();
        this.jTextArea1.setText(t);
        if (dsCauHoi.get(this.jList1.getSelectedIndex()) instanceof CauHoiTL) {
            this.jRadioButton2.setSelected(true);
            String[] a = new String[1];
            a[0] = ((CauHoiTL) dsCauHoi.get(this.jList1.getSelectedIndex())).getDapAn();
            this.jList2.setListData(a);
            this.jCo_Chuong.setSelectedItem(((CauHoiTL) dsCauHoi.get(this.jList1.getSelectedIndex())).getchuong());
            this.jCo_DoKho.setSelectedItem(((CauHoiTL) dsCauHoi.get(this.jList1.getSelectedIndex())).getdoKho());
        }
        if (dsCauHoi.get(this.jList1.getSelectedIndex()) instanceof CauHoiTN) {
            this.jRadioButton1.setSelected(true);
            String[] a = new String[dsCauHoi.get(this.jList1.getSelectedIndex()).getsoLuongDapAn()];
            for (int i = 0; i < dsCauHoi.get(this.jList1.getSelectedIndex()).getsoLuongDapAn(); i++) {
                a[i] = ((CauHoiTN) dsCauHoi.get(this.jList1.getSelectedIndex())).getdsDapAn().get(i);
            }
            this.jList2.setListData(a);
            this.jCo_Chuong.setSelectedItem(((CauHoiTN) dsCauHoi.get(this.jList1.getSelectedIndex())).getchuong());
            this.jCo_DoKho.setSelectedItem(((CauHoiTN) dsCauHoi.get(this.jList1.getSelectedIndex())).getdoKho());
        }

    }//GEN-LAST:event_jList1MouseClicked

    private void jLabel_them_cauHoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_them_cauHoiMouseClicked

        this.setData(-1);

    }//GEN-LAST:event_jLabel_them_cauHoiMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // xu ly su kien dao dap an
        int selectedIndex = this.jList1.getSelectedIndex();
        CauHoi cauhoiIndex = this.dsCauHoi.get(selectedIndex);
        if (cauhoiIndex instanceof CauHoiTN) {
            ((CauHoiTN) cauhoiIndex).daoDapAn();
        }
        this.jList1.setSelectedIndex(selectedIndex);
        this.setData(selectedIndex);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        int selectedIndexCauHoi = this.jList1.getSelectedIndex();
        int selectedIndexDapAn = this.jList2.getSelectedIndex();
        if (selectedIndexDapAn < 0) {
            return;
        }
        CauHoi ch = this.dsCauHoi.get(selectedIndexCauHoi);
        if (ch instanceof CauHoiTN) {
            ((CauHoiTN) ch).xoaDapAn(selectedIndexDapAn);

        } else {
            ((CauHoiTL) ch).setdapAn("");
        }
        this.jList1.setSelectedIndex(selectedIndexCauHoi);
        this.setData(selectedIndexCauHoi);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jB_ThemDApanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ThemDApanActionPerformed
        // Them dap an
        int selectedIndexCauHoi = this.jList1.getSelectedIndex();
        CauHoi ch = this.dsCauHoi.get(selectedIndexCauHoi);
        if (ch instanceof CauHoiTN) {
            String dapan = this.jTextField_Them_dap_an.getText();
            if (this.jCheckBox_dap_an_dung.isSelected()) {
                dapan = "~" + dapan;
            }
            ((CauHoiTN) ch).themDapAn(dapan);
        }
        this.setData(selectedIndexCauHoi);
    }//GEN-LAST:event_jB_ThemDApanActionPerformed

    private void jB_sua_dap_anActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_sua_dap_anActionPerformed
        // sua dap an
        int selectedIndexCauHoi = this.jList1.getSelectedIndex();;
        int selectedIndexDapAn = this.jList2.getSelectedIndex();
        if (selectedIndexDapAn == -1) {
            return;
        }
        String dapan = this.jTextField_Them_dap_an.getText();
        CauHoi ch = this.dsCauHoi.get(selectedIndexCauHoi);
        if (ch instanceof CauHoiTL) {
            ((CauHoiTL) ch).setdapAn(dapan);
        } else {
            if (this.jCheckBox_dap_an_dung.isSelected()) {
                dapan = "~" + dapan;
            }
            ((CauHoiTN) ch).setdapAn(selectedIndexDapAn, dapan);
        }
        this.setData(selectedIndexCauHoi);


    }//GEN-LAST:event_jB_sua_dap_anActionPerformed

    private void jL_Xoa_CauHoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_Xoa_CauHoiMouseClicked
        // xoa cau hoi
        int selectedIndexCauHoi = this.jList1.getSelectedIndex();
        if (selectedIndexCauHoi == -1) {
            return;
        }

        this.dsCauHoi.remove(selectedIndexCauHoi);
        this.setData_ds_CauHoi(dsCauHoi);
        this.setData(0);

    }//GEN-LAST:event_jL_Xoa_CauHoiMouseClicked

    private void jButton_them_cauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_them_cauHoiActionPerformed
        // TODO add your handling code here:
        if (this.jRadioButton1.isSelected()) {
            CauHoiTN ch = new CauHoiTN();
            ch.settenCauHoi(this.jTextArea1.getText());
            ch.setchuong(this.jCo_Chuong.getSelectedItem().toString());
            ch.setdoKho(this.jCo_DoKho.getSelectedItem().toString());
            ch.setmonHoc(this.monhoc.gettenMonHoc());
            this.dsCauHoi.add(ch);
            this.setData_ds_CauHoi(dsCauHoi);
            this.setData(dsCauHoi.size() - 1);
            this.jList1.setSelectedIndex(dsCauHoi.size() - 1);

        } else {
            CauHoiTL ch = new CauHoiTL();
            ch.settenCauHoi(this.jTextArea1.getText());
            ch.setchuong(this.jCo_Chuong.getSelectedItem().toString());
            ch.setdapAn("Khong co dap an");
            ch.setmonHoc(this.monhoc.gettenMonHoc());
            ch.setdoKho(this.jCo_DoKho.getSelectedItem().toString());
            this.dsCauHoi.add(ch);
            this.setData_ds_CauHoi(dsCauHoi);
            this.setData(dsCauHoi.size() - 1);
            this.jList1.setSelectedIndex(dsCauHoi.size() - 1);
        }
    }//GEN-LAST:event_jButton_them_cauHoiActionPerformed

    private void jB_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_LuuActionPerformed
        // TODO add your handling code here:
        this.monhoc.setdsCauHoi(dsCauHoi);
        this.dsMonHoc.set(selectedIndex, monhoc);

        NganHangCauHoi.ghiRaObject(dsMonHoc);
    }//GEN-LAST:event_jB_LuuActionPerformed

    private void jB_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_OKActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jB_OKActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jB_Luu;
    private javax.swing.JButton jB_OK;
    private javax.swing.JButton jB_ThemDApan;
    private javax.swing.JButton jB_sua_dap_an;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_them_cauHoi;
    private javax.swing.JCheckBox jCheckBox_dap_an_dung;
    private javax.swing.JComboBox<String> jCo_Chuong;
    private javax.swing.JComboBox<String> jCo_DoKho;
    private javax.swing.JLabel jL_Xoa_CauHoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_them_cauHoi;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField_Them_dap_an;
    // End of variables declaration//GEN-END:variables
}
